.TH hyleoroi 1 2014-oct "linux" "heatherly custom tools manual"

.SH NAME
hyleoroi \- tree structure visualization and navigation

.SH IMAGERY (see HERITAGE at bottom for more)
strong warrior nymphae who watch and protect the woods and glens

.SH SUMMARY
hyleoroi (forest watcher) is a fast, flexible, and appealing visualization
tool for heirachical, tree-structured data sets intended to provide quick
insight into proportions, imbalances, and priorities.

.SH SYNOPSIS

.B hyleoroi [ARGUMENTS]
.nf
which is the primary production version

.B hyleoroi_debug [URGENTS] [ARGUMENTS]
.nf
which can perform all production actions, but with debugging and tracing

.SH SCOPE, REASONING, and DECISION

.B situation (s).  
modern analytical and automated systems routinely produce immense, stardard,
complex, heirachical and tree structured data sets in order to convey the
results and findings of their actions.

.B complication (c).  
each of these data sets easily exceeds the average humans ability to digest
by an order of magnitude and therefore most systems generate worthless output
and little insight.

.B problem (p).  
each consumer can only relate to a small portion of the data and then only
at various levels of detail so that no one person gains anything and the
outcomes value is dubious.

.B my solution (m).  
create tools that allow datasets to be navigated, compared, and trended in
order to teach and expand a humans ability to digest, assimilate, and act on
complex data sets.

.B benefits/expectations (b)...
   -- easy understanding of heirarchical relationships
   -- rapid idenfication of largest and smallest elements
   -- easy navigation and refocusing of visualization
   -- ability to overlay multiple related data sets (or a standard)
   -- extensions to show additional data overlain on primary

.B objectives accepted (a)...
   -- sunburst, radial tree view is the primary visualization
   -- many coloration options to promote easier differentiation
   -- heirarchical navigation to allow refocusing and comparison
   -- standard view and analysis to promote greater understanding
   -- stardard vi-keys concepts to make easy for me to use
   -- simple input data structure so many programs can use
   -- input file options to allow standard config per program

.B objectives rejected (r)...
   -- no standard heirarchical, indented views (standard reporting)
   -- no simple node-link diagrams that just resemble a tree
   -- no simple block diagrams that take too much space
   -- no output other that visual

.SH STDIN FORMAT

.B 1
.RS 8
short name
.RE

.B 2
.RS 8
size
.RE

.B 2
.RS 8
count
.RE

.B 4
.RS 8
description
.RE





.SH FORMATTING OPTIONS

.B --start <path>
.RS 8
sets the start point for searching to better target results.
.RE


.SH AUTHOR
heatherlyrobert at gmail dot com

.SH HERITAGE
hyleoroi are a type of nymphs, specifically dyades.  nymphs are nature spirits
who typically inhabit, protect, and are bound to particular types of water,
landforms, trees, or plants.

dyades are the beautiful nymphs of the trees, groves, woods, glens, and
mountain forests.  They were ladies of the oaks and pines, poplar and ash,
apple and laurel.  the numbers of dyades are infinite.  unlike other dyades,
hyleoroi are warrior nymphs that patrol and protect the woodlands and are
not beholden to a particular type of tree or area.

.SH COLOPHON
this page is part of a documentation package mean to make the use of the
heatherly tools easier and faster
