.TH hyleoroi 1 2014-oct "linux" "heatherly custom tools manual"

.SH NAME
hyleoroi \- visualization and navigation of tree structures

.SH IMAGERY (see HERITAGE at bottom for more)
type of nymph or dyade, they are the watchers of the woods and glens

.SH SYNOPSIS

.B hyleoroi [ARGUMENTS]
.nf
which is the primary production version

.B hyleoroi_debug [URGENTS] [ARGUMENTS]
.nf
which can perform all hyleoroi actions, but with debugging and tracing

.SH SUMMARY
hyleoroi is a fast, simple, graphical tree viewer.

.SH STDIN FORMAT

.B 1
.RS 8
short name
.RE

.B 2
.RS 8
size
.RE

.B 2
.RS 8
count
.RE

.B 4
.RS 8
description
.RE





.SH FORMATTING OPTIONS

.B --start <path>
.RS 8
sets the start point for searching to better target results.
.RE


.SH AUTHOR
heatherlyrobert at gmail dot com

.SH HERITAGE
hyleoroi are a type of nymphs, specifically dyades.  nymphs are nature spirits
who typically inhabit, protect, and are bound to particular types of water,
landforms, trees, or plants.

dyades are the beautiful nymphs of the trees, groves, woods, glens, and
mountain forests.  They were ladies of the oaks and pines, poplar and ash,
apple and laurel.  the numbers of dyades are infinite.  unlike other dyades,
hyleoroi are warrior nymphs that patrol and protect the woodlands and are
not beholden to a particular type of tree or area.

.SH COLOPHON
this page is part of a documentation package mean to make the use of the
heatherly tools easier and faster
